# docs/swagger.yaml
openapi: 3.0.0
info:
  title: NodeJs  Boilerplate API
  version: 1.0.0
paths:
  /api/users/register:
    post:
      summary: Register a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User registered
